image: barichello/godot-ci:3.2.3

variables:
  EXPORT_NAME: invaders

stages:
  - export
  - deploy

web:
  stage: export
  script:
    - mkdir -v -p build/html5
    - godot -v --export "HTML5" ./build/html5/index.html
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/html5
